### ISSUE TITLE
nopCommerce

### ISSUE THREAD

**Issue by gordon-matt** [thangchung/awesome-dotnet-core#238]
nopCommerce is now on .NET Core as well. You might want to add that to your eCommerce section

**Comment by thangchung** [comment]
Thank you for submitting the issue. I have watched this project for a long time. As far as I know, actually in [nopCommerce](https://github.com/nopSolutions/nopCommerce) repo, they target it to `<TargetFramework>net461</TargetFramework>` for all the projects in that repo, and might not run on cross-platform easily. So that is a reason I don't put it on this list, or maybe I wrong. It would be nice if you can give me a clue that it can run on the cross-platform.

**Comment by gordon-matt** [comment]
Good point - even though it's built on .NET Core, it still targets the older framework instead of .NET Standard. I think I read somewhere that they are going to have it as fully cross platform in version 4.1, which should be released in Q2 2018... but I can't confirm 100%.

**Comment by thangchung** [comment]
@gordon-matt Thank you for your confirmation. I will keep an eye on nopCommerce. Whenever it releases a version for .NET standard, then I will add it to this awesome list.
