### ISSUE TITLE
Add Dbeeze

### ISSUE THREAD

**Issue by VladimirAkopyan** [thangchung/awesome-dotnet-core#94]
It's an embedded high-performance No-SQL library that has been around for several years. 
https://github.com/hhblaze/DBreeze
Very good, and I highly recommend it.

**Comment by thangchung** [comment]
I just have a look at it, but could not find any version of .NET Core for Web (only for UWP). Is there any version for Web or API implemented for .NET Core (.NET Standard)?

**Comment by LordMike** [comment]
The nuget package does have a `netstandard1.6` target, although the nuspec doesn't specify it exists. 

![image](https://cloud.githubusercontent.com/assets/1027111/25864439/b6de5058-34ef-11e7-811b-eb7e7dc573d7.png)

**Comment by thangchung** [comment]
@LordMike Thanks for your clarification, actually I found the project for building up those versions at https://github.com/hhblaze/DBreeze/blob/master/Deployment/Deployer/Deployer/Program.cs#L319

**Comment by LordMike** [comment]
Wow.. Everything I've seen at this library is just ... different .. :P

**Comment by thangchung** [comment]
@LordMike What's different? :)

**Comment by LordMike** [comment]
- Creating a project to actually build stuff (instead of using e.g. Msbuild, powershell or Cake)
- The nuget packages do not target multiple frameworks (nuspec), even if it includes multiple binaries
- It's the first project I've seen use "!!!" as a prefix for [Todos](https://github.com/hhblaze/DBreeze/tree/master/DBreeze) etc.
- Is the code duplicated in the UWP, NetPortable and base packages? :O

**Comment by thangchung** [comment]
@LordMike Thanks for your points. That's really interesting 👍

**Comment by hhblaze** [comment]
Here is .Net Standard 1.6 version, please check if it works in your environment. If works, we can talk about deployment.
[DBreeze.NetStandard.zip](https://github.com/thangchung/awesome-dotnet-core/files/1004955/DBreeze.NetStandard.zip)

**Comment by VladimirAkopyan** [comment]
I opened issue on Dbreese repo  if anyone wants to comment https://github.com/hhblaze/DBreeze/issues/31

**Comment by hhblaze** [comment]
Ok, Installed VS2017 and recompiled under pure .NET Standard 1.6 project.
https://www.nuget.org/packages/DBreeze/1.85.0

Don't worry about absence of customary build tools, don't forget that DBreeze supports a very wide range of Frameworks from .NET3.5 via Xamarin and .NET Portable to .NET Standard, so many files in the base projects have to be changed, depending upon type of compilations, some parts of DBreeze are cutted out to make the project compilable under certain frameworks. That's why - custom deployer. Who needs poweshall if there is pure C#? Of course, lots of .cs file have references to the base projects, if it's possible, but not all - cause not necessary.
And "!!!" should be used as candles on the Cake :)

**Comment by VladimirAkopyan** [comment]
Awesome, thanks!

**Comment by thangchung** [comment]
@VladimirAkopyan @hhblaze @LordMike Thanks, all of you for your recommendations and efforts to make it work. I have added [DBreeze](https://github.com/hhblaze/DBreeze) at [orm](https://github.com/thangchung/awesome-dotnet-core#orm) section.
